### ISSUE TITLE
Component error

### ISSUE THREAD

**Issue by mbernatovic** [dimaslz/ng-heroicons#291]
After upgrading to v0.2.2 im getting following error :

```
Error: node_modules/@dimaslz/ng-heroicons/lib/heroicons/solid/XMarkSolidIcon.component.d.ts:5:18 - error TS2314: Generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).

5     static ɵcmp: i0.ɵɵComponentDeclaration<XMarkSolidIconComponent, "x-mark-solid-icon", never, {}, {}, never, never, false>;
```

for multiple components

**Comment by dimaslz** [comment]
Hello, I just release the new version of the project. Now `@dimaslz/ng-heroicons` supports Angular project from v11 to v14, can you follow the new instructions and install the proper dependency?

If all is good, I will close this bug.

**Comment by dimaslz** [comment]
Angular 14 demo: https://stackblitz.com/edit/angular-a9ej9c?file=src/app/app.component.html
